runtime: nodejs14

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'strapi'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'postgres123'
  INSTANCE_CONNECTION_NAME: 'harvesthub-capstone:asia-southeast2:cloudsdkharvesthub'

beta_settings:
  cloud_sql_instances: 'harvesthub-capstone:asia-southeast2:cloudsdkharvesthub'
